### ISSUE TITLE
5.internal-document-searchセットアップ時の詰まりポイント

### ISSUE THREAD

**Issue by kfujisaki3** [kfujisaki3/jp-azureopenai-samples#1]
**元手順**
 [スクラッチでの開始](https://github.com/kfujisaki3/jp-azureopenai-samples/tree/main/5.internal-document-search#%E3%82%B9%E3%82%AF%E3%83%A9%E3%83%83%E3%83%81%E3%81%A7%E3%81%AE%E9%96%8B%E5%A7%8B)
- 新規に環境をデプロイする場合は、以下のコマンドを実行してください。
- az loginとaz account set -s YOUR_SUBSCRIPTION_ID後に、az ad user show --id your_account@your_tenant -o tsv --query id を実行して、操作をするユーザの AAD アカウントのオブジェクトID を取得します。
 
- 取得したオブジェクトID を環境変数AZURE_PRINCIPAL_IDにセットします。
　- Windows 環境で実行している場合は、$Env:AZURE_PRINCIPAL_ID="Your Object ID"を実行します。
　- Linux 環境で実行している場合は、export AZURE_PRINCIPAL_ID="Your Object ID"を実行します。

- azd up を実行します。- このコマンドを実行すると、Azure上に必要なリソースをデプロイし、アプリケーションのビルドとデプロイが実行されます。また、./data配下の PDF を利用して Search Index を作成します。
　- Linux 環境で実行している場合は、chmod +x scripts/prepdocs.sh
　- 
- コマンドの実行が終了すると、アプリケーションにアクセスする為の URL が表示されます。この URL をブラウザで開き、サンプルアプリケーションの利用を開始してください。

------------------------------------------------------------------------------------------------------------------------------------
細かく手順の記載がないため、解説。
全てpwsh.exeでの実行。（最初にインストールした通常のWindows Powershellと違うPowerShell 7による実行）

1.az loginコマンドを実行する。（前に行ったazd loginとは異なるコマンドのため必要。飛ばさないように）

→　az login した後、正常であれば下記情報がシェル上に表示される
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/8b24ba67-63db-40ca-9766-3aba1be8ac48)

→　問題がある場合下記のエラーが表示されることがある。
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/eb2b7131-11a2-4526-9303-fb4a6e43440f)

以下、ChatGPT回答------
エラーメッセージには、既定のディレクトリ というテナントがMFA（多要素認証）を要求していることが示されています。このテナントにログインするには、以下のコマンドを使用します。

az login --tenant 942350ba-359b-49a6-b7c4-30a8f9243f9b

---------------------

このコマンドで--tenantを指定することでログインが正常に完了する。

2. az account set -s YOUR_SUBSCRIPTION_ID　を実行する。
サブスクリプションIDは下記
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/fba91c1e-2335-4545-ba65-0e426154f665)

3.az ad user show --id your_account@your_tenant -o tsv --query id を実行して、操作をするユーザの AAD アカウントのオブジェクトID を取得する。
→　your_account@your_tenant　は　下記のユーザープリンシパル名をセットする。
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/6cb2302f-b786-4d46-9d57-7a11eb1cb4c8)

4.取得したオブジェクトID を環境変数AZURE_PRINCIPAL_IDにセットする。
環境変数設定は$Env:AZURE_PRINCIPAL_ID="Your Object ID"。

オブジェクトIDは3.のコマンド実行後に表示される文字列
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/776915ed-163d-4520-ba16-0cce28d33517)

環境変数設定のコマンド実行後、環境変数の設定がうまくいったか確認するには$Env:AZURE_PRINCIPAL_IDを実行すると良い。

5.azd up を実行。このときは下記のようにサブスクリプションの選択（1個しかない場合が多い）、リージョンの選択を行う。リージョンはOpenAI Serviceが使えるリージョンを選択するJapan Eastを選ぶ。
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/3871c330-c5cb-4044-a9bd-c483b88d217c)

実行するとデプロイがはじまる
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/6e64764d-0d0e-43cb-9da4-c477d3d8a2ab)

その後「? Enter a value for the 'vmLoginPassword' infrastructure parameter:」とvmへのログインパスワードの入力を求められる（以前に設定しているパスワードを入力するということではなく、新しく設定するという意味での入力）。
入力すると今後も使うか確認されるのでy
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/afa97350-f4a4-4f81-af51-61e8be181559)

デプロイが継続される

**Comment by kfujisaki3** [comment]
### *-追記：下に書いてある色々を試した後に下記リンクをみて、大元の管理者ユーザーでデプロイしようとするとこのエラーが起きてしまうため、ユーザーを別に作る必要があることをしる。ユーザーをたてて、ユーザーアクセス管理者に指定、サブスクリプションへのIAM権限を与えて再度デプロイ手順を1から行うとうまくデプロイできた。
https://github.com/Azure-Samples/azure-search-openai-demo/issues/4#issuecomment-1483176774*

デプロイ後のエラー解消メモ
下記エラーが出る。　Azure Cognitive Searchのリソースは作れているがIndexの作成で失敗している。

-RDBに置き換えるとDBのセットアップはできているが、テーブル作成ができていないということ。

**Ensuring search index gptkbindex exists
Traceback (most recent call last):
  File "C:\GitHub\jp-azureopenai-samples\5.internal-document-search\scripts\prepdocs.py", line 305, in <module>
    create_search_index()
  File "C:\GitHub\jp-azureopenai-samples\5.internal-document-search\scripts\prepdocs.py", line 243, in create_search_index
    if args.index not in index_client.list_index_names():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 123, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 512, in get_next
    raise HttpResponseError(response=response, model=error)
azure.core.exceptions.HttpResponseError: () Authorization failed.
Code:
Message: Authorization failed.**


このエラーが出ていてもそのほかのサービスはデプロイできているため、アプリは立ち上がるが、社内文書検索をしようとすると下記エラーがでる。ここでnot foundになっているのが本来あるはずのindex（テーブル）

![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/226d762d-4d93-4e2c-9f11-59ec09714161)



ストレージアカウントのアクセスキーをprepdocs.ps1でprepdocs.pyをたたいているときの引数に追加する。
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/298feaea-b267-40a7-a69a-1aea3bb90b75)

CLIで $Env:AZURE_STORAGEKEY = "アクセスキー名"　で環境変数を設定。

![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/78680803-fd86-4603-a26f-1efd772f554a)
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/9e6826f9-0935-48e0-b443-fea2e567478b)


ソース：
https://github.com/Azure-Samples/azure-search-openai-demo/issues/17#issuecomment-1497757338
英語版のリポジトリなので微妙にソースコードが違う＆半年前なのでソースコードが今はかわっていることもあり、このソースで指摘しているように他の引数も設定する必要はなかった（すでに今のps1には設定されてた）

**Comment by kfujisaki3** [comment]
User
prepdocs.py
Python
C:\GitHub\jp-azureopenai-samples\5.internal-document-search\scripts\prepdocs.py:26: SyntaxWarning: invalid escape sequence '\d'
  epilog="Example: prepdocs.py '..\data\*' --storageaccount myaccount --container mycontainer --searchservice mysearch --index myindex -v"
C:\GitHub\jp-azureopenai-samples\5.internal-document-search\scripts\prepdocs.py:105: SyntaxWarning: invalid escape sequence '\d'
  blobs = filter(lambda b: re.match(f"{prefix}-\d+\.pdf", b), blob_container.list_blob_names(name_starts_with=os.path.splitext(os.path.basename(prefix))[0]))

エスケープの警告も出てくるので、下記のようにバックスラッシュを重ねるように2か所修正

epilog="Example: prepdocs.py '..\\data\\*' --storageaccount myaccount --container mycontainer --searchservice mysearch --index myindex -v"

**Comment by kfujisaki3** [comment]
### 環境変数
環境変数を用いるツールも多々あるため、とりあえず以下を設定しておくと幸せになれる。

​HTTP_PROXY=http://proxy.unisys.co.jp:8080/
http_proxy=http://proxy.unisys.co.jp:8080/
HTTPS_PROXY=http://proxy.unisys.co.jp:8080/
​https_proxy=http://proxy.unisys.co.jp:8080/

登録しないとCLIでAzureと通信する際にSSL認証エラーがおきる

エラー------------------
Running "prepdocs.py"
Assume azd credential
Ensuring search index gptkbindex exists
Traceback (most recent call last):
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\prepdocs.py", line 305, in <module>
    create_search_index()
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\prepdocs.py", line 243, in create_search_index
    if args.index not in index_client.list_index_names():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 123, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 504, in get_next
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 230, in run
    return first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 197, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 553, in send
    raise err
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 531, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 126, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 119, in send
    self._sender.send(request.http_request, **request.context.options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GitHub\jp-azureopenai-samples-main\5.internal-document-search\scripts\.venv\Lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 381, in send
    raise error
azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

**Comment by ksuzuki44** [comment]
【鈴木備忘】
■現象
デプロイ中に以下のエラー発生
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'ebd7fa66-eaed-4aa8-b109-675f0de48c23'. See inner errors for details.
InsufficientQuota: The specified capacity '120' of account deployment is bigger than available capacity '60' for UsageName 'Tokens Per Minute (thousands) - GPT-35-Turbo'.

TraceID: a8a797bbd9b0b4182f519266c2edce8d

![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/104112408/20230910-61de-4ec0-99c6-7df413da58fe)

■対応
モデルのクオーターを120から10に変更

![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/104112408/450a6081-66d1-4f7e-ac52-3c667ad34f2a)

**Comment by ksuzuki44** [comment]
【鈴木備忘】
■現象
デプロイ中に以下のエラー発生
SecurityError: File C:\jp-azureopenai-samples-main\5.internal-document-search\scripts\prepdocs.ps1 cannot be loaded. The file C:\jp-azureopenai-samples-main\5.internal-document-search\scripts\prepdocs.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.

ERROR: failed running post hooks: 'postprovision' hook failed with exit code: '1', Path: '.\scripts\prepdocs.ps1'. : exit code: 1

■対応
下記URLのやり方を実施
https://kondeneenen.com/powershell_digitalsignature/

![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/104112408/9f788981-5f41-4a0c-beb1-979fed149028)

**Comment by ysuzuki109** [comment]
> 【鈴木備忘】 ■現象 デプロイ中に以下のエラー発生 ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:
> 
> Deployment Error Details: InvalidTemplateDeployment: The template deployment 'openai' is not valid according to the validation procedure. The tracking id is 'ebd7fa66-eaed-4aa8-b109-675f0de48c23'. See inner errors for details. InsufficientQuota: The specified capacity '120' of account deployment is bigger than available capacity '60' for UsageName 'Tokens Per Minute (thousands) - GPT-35-Turbo'.
> 
> TraceID: a8a797bbd9b0b4182f519266c2edce8d
> 
> ![image](https://user-images.githubusercontent.com/104112408/276085084-20230910-61de-4ec0-99c6-7df413da58fe.png)
> 
> ■対応 モデルのクオーターを120から10に変更
> 
> ![image](https://user-images.githubusercontent.com/104112408/276087668-450a6081-66d1-4f7e-ac52-3c667ad34f2a.png)


【鈴木（友）追記】
bicepファイル（Azure リソースをデプロイするための固有言語）にクォータを設定することでも対応可能のようです。
以下のフォルダを参照して、「main.bicep」というファイルをメモ帳等で開く。

<自分がリポジトリをクローンした任意のディレクトリ>\jp-azureopenai-samples\5.internal-document-search\infra\main.bicep

main.bicepの以下のコードにおいて、
179行目と191行目にあるCapacityを120から任意の値に変更してください（以下の場合は10に変更）。

main.bicep158行目以降
module openAi 'core/ai/cognitiveservices.bicep' = {
  name: 'openai'
  scope: openAiResourceGroup
  params: {
    name: !empty(openAiServiceName) ? openAiServiceName : '${abbrs.cognitiveServicesAccounts}${resourceToken}'
    location: openAiResourceGroupLocation
    tags: tags
    sku: {
      name: openAiSkuName
    }
    deployments: [
      {
        name: openAiGpt35TurboDeploymentName
        model: {
          format: 'OpenAI'
          name: 'gpt-35-turbo'
          version: '0613'
        }
        sku: {
          name: 'Standard'
          capacity: 10
        }
      }
      {
        name: openAiGpt35Turbo16kDeploymentName
        model: {
          format: 'OpenAI'
          name: 'gpt-35-turbo-16k'
          version: '0613'
        }
        sku: {
          name: 'Standard'
          capacity: 10
        }
      }
    ]
    publicNetworkAccess: isPrivateNetworkEnabled ? 'Disabled' : 'Enabled'
  }
}
※鈴木の環境では上記のような行数でしたが、
環境によって異なる可能性もあるので同様のコードを探してください。

以下のサイトが今回のエラーについて触れていたので参考にしましたが
親切に解説してあるわけではなかったので、
capacityを変更する方法に当たりをつけてやってみた感じです。
そのため、他にももっとスマートな方法はあるかもしれません。
https://github.com/Azure-Samples/azure-search-openai-demo/issues/307

**Comment by kfujisaki3** [comment]
![image](https://github.com/kfujisaki3/jp-azureopenai-samples/assets/93004470/bbd9ffda-456e-421c-87ba-815724826db3)

リソースを消した後再デプロイしようとすると発生。一部のリソースはソフトデリートであり、完全に消えない。

この場合の対象リソースは下記。

Cognitive Servicesアカウント: /subscriptions/b99cfed7-3aef-4a0b-b563-8c594ca1a9ee/resourceGroups/rg-new-env_kf/providers/Microsoft.CognitiveServices/accounts/cog-wr2tq32t5ctqm
別のCognitive Servicesアカウント（Form Recognizer用）: /subscriptions/b99cfed7-3aef-4a0b-b563-8c594ca1a9ee/resourceGroups/rg-new-env_kf/providers/Microsoft.CognitiveServices/accounts/cog-fr-wr2tq32t5ctqm

パージ（完全削除）のための下記コマンドをCLIから実行すると消える。
